import { Product, Mission, Achievement, Level, Reward } from '../types';

export const mockProducts: Product[] = [
  // Skincare
  {
    id: '1',
    name: 'Hydrating Face Serum',
    description: 'A lightweight, fast-absorbing serum that delivers intense hydration.',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571',
    category: 'Skincare',
    pointsValue: 50,
  },
  {
    id: '2',
    name: 'Vitamin C Brightening Cream',
    description: 'Brightens and evens skin tone while providing antioxidant protection.',
    price: 39.99,
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b',
    category: 'Skincare',
    pointsValue: 40,
  },
  {
    id: '3',
    name: 'Gentle Exfoliating Toner',
    description: 'Removes dead skin cells and unclogs pores for a radiant complexion.',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881',
    category: 'Skincare',
    pointsValue: 30,
  },

  // Makeup
  {
    id: '4',
    name: 'Matte Lipstick',
    description: 'Long-lasting, highly pigmented matte lipstick.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa',
    category: 'Makeup',
    pointsValue: 25,
  },
  {
    id: '5',
    name: 'Liquid Foundation',
    description: 'Full coverage foundation with a natural finish.',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
    category: 'Makeup',
    pointsValue: 35,
  },
  {
    id: '6',
    name: 'Eyeshadow Palette',
    description: 'Versatile palette with 12 highly pigmented shades.',
    price: 44.99,
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796',
    category: 'Makeup',
    pointsValue: 45,
  },

  // Haircare
  {
    id: '7',
    name: 'Natural Hair Mask',
    description: 'Deep conditioning treatment for all hair types.',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388',
    category: 'Haircare',
    pointsValue: 35,
  },
  {
    id: '8',
    name: 'Volumizing Shampoo',
    description: 'Adds body and volume to fine, limp hair.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da',
    category: 'Haircare',
    pointsValue: 25,
  },
  {
    id: '9',
    name: 'Heat Protectant Spray',
    description: 'Protects hair from heat damage up to 450°F.',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
    category: 'Haircare',
    pointsValue: 20,
  },

  // Fragrance
  {
    id: '10',
    name: 'Floral Perfume',
    description: 'Light and airy floral scent perfect for everyday wear.',
    price: 59.99,
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539',
    category: 'Fragrance',
    pointsValue: 60,
  },
  {
    id: '11',
    name: 'Woody Eau de Parfum',
    description: 'Rich and sophisticated woody fragrance.',
    price: 69.99,
    image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f',
    category: 'Fragrance',
    pointsValue: 70,
  },
  {
    id: '12',
    name: 'Citrus Body Mist',
    description: 'Refreshing citrus scent in a lightweight mist.',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1595425970375-3f4c2f1f1f1f',
    category: 'Fragrance',
    pointsValue: 30,
  },

  // Bath & Body
  {
    id: '13',
    name: 'Luxury Bath Oil',
    description: 'Nourishing bath oil with essential oils.',
    price: 39.99,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
    category: 'Bath & Body',
    pointsValue: 40,
  },
  {
    id: '14',
    name: 'Body Scrub',
    description: 'Exfoliating body scrub with natural ingredients.',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
    category: 'Bath & Body',
    pointsValue: 30,
  },
  {
    id: '15',
    name: 'Hand Cream',
    description: 'Rich, moisturizing hand cream with shea butter.',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
    category: 'Bath & Body',
    pointsValue: 20,
  }
];

export const mockMissions: Mission[] = [
  {
    id: '1',
    title: 'First Purchase',
    description: 'Make your first purchase to earn bonus points',
    type: 'purchase',
    difficulty: 'easy',
    pointsReward: 100,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'purchase',
      value: 1,
      currentValue: 0,
    },
  },
  {
    id: '2',
    title: 'Product Review',
    description: 'Write a review for any purchased product',
    type: 'review',
    difficulty: 'easy',
    pointsReward: 50,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'review',
      value: 1,
      currentValue: 0,
    },
  },
  {
    id: '3',
    title: 'Social Share',
    description: 'Share your purchase on social media',
    type: 'social',
    difficulty: 'easy',
    pointsReward: 75,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'social',
      value: 1,
      currentValue: 0,
    },
  },
  {
    id: '4',
    title: 'Weekly Shopper',
    description: 'Make 3 purchases in a week',
    type: 'weekly',
    difficulty: 'medium',
    pointsReward: 200,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'purchase',
      value: 3,
      currentValue: 0,
    },
  },
  {
    id: '5',
    title: 'Review Master',
    description: 'Write 5 product reviews',
    type: 'review',
    difficulty: 'medium',
    pointsReward: 250,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'review',
      value: 5,
      currentValue: 0,
    },
  },
  {
    id: '6',
    title: 'Social Butterfly',
    description: 'Share 5 purchases on social media',
    type: 'social',
    difficulty: 'medium',
    pointsReward: 300,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'social',
      value: 5,
      currentValue: 0,
    },
  },
  {
    id: '7',
    title: 'Beauty Expert',
    description: 'Purchase products from 5 different categories',
    type: 'purchase',
    difficulty: 'hard',
    pointsReward: 500,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'category',
      value: 5,
      currentValue: 0,
    },
  },
  {
    id: '8',
    title: 'Loyal Customer',
    description: 'Make 10 purchases in a month',
    type: 'purchase',
    difficulty: 'hard',
    pointsReward: 1000,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'purchase',
      value: 10,
      currentValue: 0,
    },
  },
  {
    id: '9',
    title: 'Daily Check-in',
    description: 'Check in to the app for 7 consecutive days',
    type: 'daily',
    difficulty: 'easy',
    pointsReward: 150,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'checkin',
      value: 7,
      currentValue: 0,
    },
  },
  {
    id: '10',
    title: 'Refer a Friend',
    description: 'Invite a friend to join the loyalty program',
    type: 'special',
    difficulty: 'medium',
    pointsReward: 400,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'referral',
      value: 1,
      currentValue: 0,
    },
  },
  {
    id: '11',
    title: 'Skincare Specialist',
    description: 'Purchase 3 skincare products',
    type: 'purchase',
    difficulty: 'medium',
    pointsReward: 300,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'category',
      value: 3,
      currentValue: 0,
    },
  },
  {
    id: '12',
    title: 'Makeup Maven',
    description: 'Purchase 3 makeup products',
    type: 'purchase',
    difficulty: 'medium',
    pointsReward: 300,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'category',
      value: 3,
      currentValue: 0,
    },
  },
  {
    id: '13',
    title: 'Fragrance Fanatic',
    description: 'Purchase 2 fragrances',
    type: 'purchase',
    difficulty: 'medium',
    pointsReward: 400,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'category',
      value: 2,
      currentValue: 0,
    },
  },
  {
    id: '14',
    title: 'Haircare Hero',
    description: 'Purchase 3 haircare products',
    type: 'purchase',
    difficulty: 'medium',
    pointsReward: 300,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'category',
      value: 3,
      currentValue: 0,
    },
  },
  {
    id: '15',
    title: 'Bath & Body Bliss',
    description: 'Purchase 3 bath & body products',
    type: 'purchase',
    difficulty: 'medium',
    pointsReward: 300,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'category',
      value: 3,
      currentValue: 0,
    },
  },
  {
    id: '16',
    title: 'Weekend Warrior',
    description: 'Make a purchase during the weekend',
    type: 'special',
    difficulty: 'easy',
    pointsReward: 150,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'weekend_purchase',
      value: 1,
      currentValue: 0,
    },
  },
  {
    id: '17',
    title: 'Early Bird Special',
    description: 'Make a purchase before 10 AM',
    type: 'special',
    difficulty: 'easy',
    pointsReward: 100,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'morning_purchase',
      value: 1,
      currentValue: 0,
    },
  },
  {
    id: '18',
    title: 'Social Media Star',
    description: 'Get 10 likes on your social media posts',
    type: 'social',
    difficulty: 'medium',
    pointsReward: 200,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'social_likes',
      value: 10,
      currentValue: 0,
    },
  },
  {
    id: '19',
    title: 'Review Champion',
    description: 'Write 3 detailed product reviews with photos',
    type: 'review',
    difficulty: 'medium',
    pointsReward: 300,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'review_with_photo',
      value: 3,
      currentValue: 0,
    },
  },
  {
    id: '20',
    title: 'Loyalty Legend',
    description: 'Complete 5 missions in a week',
    type: 'special',
    difficulty: 'hard',
    pointsReward: 1000,
    isCompleted: false,
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    requirements: {
      type: 'missions_completed',
      value: 5,
      currentValue: 0,
    },
  },
];

export const mockAchievements: Achievement[] = [
  {
    id: '1',
    title: 'Beauty Enthusiast',
    description: 'Purchase 5 beauty products',
    icon: '🌟',
  },
  {
    id: '2',
    title: 'Review Master',
    description: 'Write 10 product reviews',
    icon: '📝',
  },
  {
    id: '3',
    title: 'Social Butterfly',
    description: 'Share 5 purchases on social media',
    icon: '🦋',
  },
  {
    id: '4',
    title: 'Early Adopter',
    description: 'Be among the first 100 members',
    icon: '🚀',
  },
  {
    id: '5',
    title: 'Loyal Customer',
    description: 'Make 20 purchases',
    icon: '👑',
  },
  {
    id: '6',
    title: 'Beauty Expert',
    description: 'Purchase from all product categories',
    icon: '💄',
  },
  {
    id: '7',
    title: 'Social Influencer',
    description: 'Get 50 likes on your social shares',
    icon: '📱',
  },
  {
    id: '8',
    title: 'Review Champion',
    description: 'Write 25 detailed product reviews',
    icon: '🏆',
  },
  {
    id: '9',
    title: 'Early Bird',
    description: 'Make a purchase within the first hour of a sale',
    icon: '⏰',
  },
  {
    id: '10',
    title: 'Referral Pro',
    description: 'Invite 5 friends to join',
    icon: '🤝',
  },
];

export const mockLevels: Level[] = [
  {
    level: 1,
    name: 'Beauty Beginner',
    requiredPoints: 0,
    benefits: [
      'Earn 1 point per $1 spent',
      'Access to basic rewards',
    ],
  },
  {
    level: 2,
    name: 'Beauty Explorer',
    requiredPoints: 1000,
    benefits: [
      'Earn 1.5 points per $1 spent',
      'Access to premium rewards',
      'Free shipping on orders over $50',
    ],
  },
  {
    level: 3,
    name: 'Beauty Expert',
    requiredPoints: 5000,
    benefits: [
      'Earn 2 points per $1 spent',
      'Access to exclusive rewards',
      'Free shipping on all orders',
      'Early access to new products',
    ],
  },
];

export const mockRewards: Reward[] = [
  {
    id: '1',
    title: '10% Off Next Purchase',
    description: 'Get 10% off your next purchase',
    pointsCost: 500,
    type: 'discount',
    value: 10,
    isAvailable: true,
  },
  {
    id: '2',
    title: 'Free Shipping',
    description: 'Free shipping on your next order',
    pointsCost: 300,
    type: 'service',
    value: 100,
    isAvailable: true,
  },
  {
    id: '3',
    title: '20% Off Next Purchase',
    description: 'Get 20% off your next purchase',
    pointsCost: 1000,
    type: 'discount',
    value: 20,
    isAvailable: true,
  },
  {
    id: '4',
    title: 'Free Gift with Purchase',
    description: 'Get a free gift with your next purchase',
    pointsCost: 800,
    type: 'product',
    value: 1,
    isAvailable: true,
  },
  {
    id: '5',
    title: 'VIP Early Access',
    description: 'Get early access to new products',
    pointsCost: 1500,
    type: 'service',
    value: 1,
    isAvailable: true,
  },
  {
    id: '6',
    title: '25% Off Next Purchase',
    description: 'Get 25% off your next purchase',
    pointsCost: 2000,
    type: 'discount',
    value: 25,
    isAvailable: true,
  },
  {
    id: '7',
    title: 'Free Product',
    description: 'Get a free product of your choice',
    pointsCost: 2500,
    type: 'product',
    value: 1,
    isAvailable: true,
  },
  {
    id: '8',
    title: 'Birthday Bonus',
    description: 'Double points on your birthday month',
    pointsCost: 1000,
    type: 'service',
    value: 2,
    isAvailable: true,
  },
  {
    id: '9',
    title: 'Exclusive Event Access',
    description: 'Access to exclusive beauty events',
    pointsCost: 3000,
    type: 'service',
    value: 1,
    isAvailable: true,
  },
  {
    id: '10',
    title: 'Personal Shopping Session',
    description: 'One-hour personal shopping session',
    pointsCost: 5000,
    type: 'service',
    value: 1,
    isAvailable: true,
  },
]; 